"""Bit-exact seeded compatibility fixtures for the legacy SH-WFS adapters.

The expected hashes were generated by executing ``git show`` versions of
``HEAD:src/reconstruction.py``, ``HEAD:src/shwfs_detector.py``, and
``HEAD:src/synthetic_instrument_data.py`` together in an isolated module
namespace at commit ``9c4816c094249b49d4f9a1fd182e39ea264252e5``.

The selected geometry retains four fully illuminated central lenslets whose
historical local FFT canvas equals the canonical fixed sampling canvas.  Thus
these fixtures isolate compatibility routing and record adaptation rather than
freezing a known edge-lenslet sampling defect.  ``seed=None`` is intentionally
checked only structurally because it requests a non-replayable realization.
"""

from __future__ import annotations

import hashlib

import numpy as np

from shwfs_ao.legacy import shwfs_detector
from shwfs_ao.legacy import synthetic_instrument_data as synthetic


_HEAD_FIXTURE_COMMIT = "9c4816c094249b49d4f9a1fd182e39ea264252e5"

_LOW_LEVEL_HASHES = {
    "centers": "0dda02d3fd08224715331846c380b5642895f14f68ecf32cdbb1b6bc75156f85",
    "shifts": "0672fde6cf41246281c7877b47c1b1de1aa62d6efaa335ad237377550ef0bdf5",
    "centroids": "066015aba8288fce69036f3e413744a090e5491888cdaaabf32b471540024dae",
    "reference": "066015aba8288fce69036f3e413744a090e5491888cdaaabf32b471540024dae",
    "fluxes": "5aa1a3ce701ee3386dc716f3e97ffdbc73f7bcbb54165c28a927b981feefc0c3",
    "valid": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "spots": "2ff408f234cae5a6fa415bb63bde17a09d961ba8f5b12f0a4cb1f9b32e6b63fc",
}

_SYNTHETIC_HASHES = {
    "centers_m": "0dda02d3fd08224715331846c380b5642895f14f68ecf32cdbb1b6bc75156f85",
    "reference_centroids_px": "066015aba8288fce69036f3e413744a090e5491888cdaaabf32b471540024dae",
    "shifts_px": "0672fde6cf41246281c7877b47c1b1de1aa62d6efaa335ad237377550ef0bdf5",
    "centroids_px": "066015aba8288fce69036f3e413744a090e5491888cdaaabf32b471540024dae",
    "fluxes_e": "cf80099dd5034326e4404846e67fe3f497ba2c50626c1c6befa56b740d965d5f",
    "valid": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "total_flux_e": "3defe87709522390efaa5bdb8f86157ef817108159df093cca7761982ade6a11",
    "background_e": "750b62584eeab2bf39c1783a347cb1dfaf29466ad4c7e054a57b2d3fc2a80ccc",
    "peak_snr": "4635f689e84d6aae0f5dd9dae234887d775cffcdac2285cb24712b5327783103",
    "total_snr": "cf40461e22854ba59c1456e4755cfda6de54ca607276e7e7c339f24e0729c48e",
    "centroid_sigma_px": "1a8dc3e3cce923f84c8e99438ccbc223d7803148aaebb5b604837466fa3a844c",
    "window_clipping_fraction": "f32b9681d31a01647247beb1df68e5407021a69076c6b0bf9e1107df1e6e258f",
    "valid_by_flux": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "valid_by_snr": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "valid_by_uncertainty": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "valid_by_clipping": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "spots": "48b38e2296c2dadf47a30428a0840a5326f22db180c849371c4f401f5fa80bea",
}

_SYNTHETIC_PER_FRAME_PRNU_HASHES = {
    "reference_centroids_px": "066015aba8288fce69036f3e413744a090e5491888cdaaabf32b471540024dae",
    "shifts_px": "e0578c4bcaad9b8ba7d0959317fd55ac907fd7730ddd10ac7184f19625c2dc10",
    "centroids_px": "ac7b85c6031c0b5f1e488419cba02c10d7b43ef6e3db2db462329ac74adb75a9",
    "fluxes_e": "7531d5d50df307bab99de30a7bed563365a2cd21d0e3f68b807aaf4972ec77fc",
    "valid": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "total_flux_e": "3defe87709522390efaa5bdb8f86157ef817108159df093cca7761982ade6a11",
    "background_e": "750b62584eeab2bf39c1783a347cb1dfaf29466ad4c7e054a57b2d3fc2a80ccc",
    "peak_snr": "4635f689e84d6aae0f5dd9dae234887d775cffcdac2285cb24712b5327783103",
    "total_snr": "cf40461e22854ba59c1456e4755cfda6de54ca607276e7e7c339f24e0729c48e",
    "centroid_sigma_px": "1a8dc3e3cce923f84c8e99438ccbc223d7803148aaebb5b604837466fa3a844c",
    "window_clipping_fraction": "f32b9681d31a01647247beb1df68e5407021a69076c6b0bf9e1107df1e6e258f",
    "valid_by_flux": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "valid_by_snr": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "valid_by_uncertainty": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "valid_by_clipping": "d050f288bd8632689deffe8e063d5537694befc10ffd314797a6a2532f07360c",
    "spots": "5eebde7e153ea360467e2548c30568638207f6e2723508ce5e45c51d6d16a194",
}


def _array_hash(values: np.ndarray) -> str:
    """Hash shape, canonical dtype, and exact C-order bytes."""

    array = np.asarray(values)
    if array.dtype.kind == "f":
        canonical = np.ascontiguousarray(array, dtype="<f8")
    elif array.dtype.kind == "b":
        canonical = np.ascontiguousarray(array, dtype=np.uint8)
    else:
        canonical = np.ascontiguousarray(array)
    digest = hashlib.sha256()
    digest.update(str(canonical.shape).encode("ascii"))
    digest.update(canonical.dtype.str.encode("ascii"))
    digest.update(canonical.tobytes(order="C"))
    return digest.hexdigest()


def _sampled_pupil() -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    axis = np.linspace(-0.5, 0.5, 24)
    x_m, y_m = np.meshgrid(axis, axis)
    pupil_mask = np.hypot(x_m, y_m) <= 0.5
    phase_rad = np.where(
        pupil_mask,
        0.17 * x_m - 0.11 * y_m + 0.035 * (x_m**2 - y_m**2),
        np.nan,
    )
    return x_m, y_m, pupil_mask, phase_rad


def _low_level_measurement(seed: int | None):
    x_m, y_m, pupil_mask, phase_rad = _sampled_pupil()
    return shwfs_detector.measure_centroid_shifts(
        phase_rad,
        pupil_mask,
        x_m,
        y_m,
        n_lenslets=4,
        min_fill=1.0,
        pad_factor=3,
        photons=650.0,
        read_noise_e=0.65,
        background_e=0.2,
        threshold_fraction=0.99,
        subtract_minimum=False,
        detector_window_size=None,
        seed=seed,
        return_spots=True,
        return_diagnostics=True,
    )


def _synthetic_calibration(
    *,
    prnu_rms: float = 0.0,
) -> synthetic.DetectorShwfsCalibration:
    geometry = synthetic.ShwfsGeometryConfig(
        telescope_diameter_m=1.0,
        n_pupil_pixels=24,
        n_lenslets=4,
        min_fill_fraction=1.0,
        pad_factor=3,
        detector_window_px=None,
        threshold_fraction=0.99,
        subtract_minimum=False,
    )
    detector = synthetic.DetectorConfig(
        photons_per_subap_frame=650.0,
        read_noise_e=0.65,
        dark_e_per_s=1.5,
        background_e_per_pixel_frame=0.2,
        full_well_e=None,
        qe=0.83,
        bad_pixel_mask=None,
        prnu_rms=prnu_rms,
        exposure_s=0.002,
    )
    return synthetic.build_detector_shwfs_calibration(geometry, detector)


def test_low_level_seeded_measurement_matches_pre_refactor_bytes() -> None:
    centers, shifts, spots, diagnostics = _low_level_measurement(314159)
    actual = {
        "centers": _array_hash(centers),
        "shifts": _array_hash(shifts),
        "centroids": _array_hash(diagnostics["centroids"]),
        "reference": _array_hash(diagnostics["reference"]),
        "fluxes": _array_hash(diagnostics["fluxes"]),
        "valid": _array_hash(diagnostics["valid"]),
        "spots": _array_hash(np.stack(spots)),
    }

    assert actual == _LOW_LEVEL_HASHES
    assert diagnostics["n_valid"] == diagnostics["n_total"] == 4
    assert diagnostics["valid_centroid_frac"] == 1.0
    assert [spot.shape for spot in spots] == [(18, 18)] * 4


def test_synthetic_seeded_measurement_matches_pre_refactor_bytes() -> None:
    calibration = _synthetic_calibration()
    phase_rad = np.where(calibration.pupil_mask, 0.0, np.nan)
    measurement = synthetic.measure_detector_shwfs(
        phase_rad,
        calibration,
        include_noise=True,
        seed=271828,
        return_spots=True,
    )
    assert measurement.spots is not None
    actual = {
        "centers_m": _array_hash(calibration.centers_m),
        "reference_centroids_px": _array_hash(
            calibration.reference_centroids_px
        ),
        **{
            name: _array_hash(getattr(measurement, name))
            for name in (
                "shifts_px",
                "centroids_px",
                "fluxes_e",
                "valid",
                "total_flux_e",
                "background_e",
                "peak_snr",
                "total_snr",
                "centroid_sigma_px",
                "window_clipping_fraction",
                "valid_by_flux",
                "valid_by_snr",
                "valid_by_uncertainty",
                "valid_by_clipping",
            )
        },
        "spots": _array_hash(np.stack(measurement.spots)),
    }

    assert actual == _SYNTHETIC_HASHES
    assert measurement.valid_centroid_frac == 1.0
    assert [spot.shape for spot in measurement.spots] == [(18, 18)] * 4


def test_synthetic_per_frame_prnu_matches_ideal_reference_and_seeded_bytes() -> None:
    calibration = _synthetic_calibration(prnu_rms=0.2)
    np.testing.assert_array_equal(
        calibration.reference_centroids_px,
        np.tile(np.asarray([[0.5, -0.5]]), (4, 1)),
    )
    measurement = synthetic.measure_detector_shwfs(
        np.where(calibration.pupil_mask, 0.0, np.nan),
        calibration,
        include_noise=True,
        seed=161803,
        return_spots=True,
    )
    assert measurement.spots is not None
    actual = {
        "reference_centroids_px": _array_hash(
            calibration.reference_centroids_px
        ),
        **{
            name: _array_hash(getattr(measurement, name))
            for name in (
                "shifts_px",
                "centroids_px",
                "fluxes_e",
                "valid",
                "total_flux_e",
                "background_e",
                "peak_snr",
                "total_snr",
                "centroid_sigma_px",
                "window_clipping_fraction",
                "valid_by_flux",
                "valid_by_snr",
                "valid_by_uncertainty",
                "valid_by_clipping",
            )
        },
        "spots": _array_hash(np.stack(measurement.spots)),
    }

    assert actual == _SYNTHETIC_PER_FRAME_PRNU_HASHES
    np.testing.assert_array_equal(
        measurement.shifts_px,
        np.asarray(
            [
                [0.0, 0.0],
                [0.0, 1.0],
                [1.0, 0.0],
                [0.0, 0.0],
            ]
        ),
    )
    assert measurement.valid_centroid_frac == 1.0
    assert [spot.shape for spot in measurement.spots] == [(18, 18)] * 4


def test_low_level_seed_none_is_structurally_valid_without_exact_fixture() -> None:
    centers, shifts, spots, diagnostics = _low_level_measurement(None)

    assert centers.shape == shifts.shape == (4, 2)
    assert diagnostics["centroids"].shape == (4, 2)
    assert diagnostics["reference"].shape == (4, 2)
    assert diagnostics["fluxes"].shape == diagnostics["valid"].shape == (4,)
    assert diagnostics["valid"].dtype == np.dtype(bool)
    assert np.all(np.isfinite(diagnostics["fluxes"]))
    assert np.all(diagnostics["fluxes"] >= 0.0)
    assert len(spots) == 4
    assert all(spot.shape == (18, 18) for spot in spots)
    assert all(np.all(np.isfinite(spot)) for spot in spots)


def test_synthetic_seed_none_is_structurally_valid_without_exact_fixture() -> None:
    calibration = _synthetic_calibration()
    measurement = synthetic.measure_detector_shwfs(
        np.where(calibration.pupil_mask, 0.0, np.nan),
        calibration,
        include_noise=True,
        seed=None,
        return_spots=True,
    )

    assert measurement.shifts_px.shape == measurement.centroids_px.shape == (4, 2)
    assert measurement.fluxes_e.shape == measurement.valid.shape == (4,)
    assert measurement.valid.dtype == np.dtype(bool)
    assert np.all(np.isfinite(measurement.fluxes_e))
    assert np.all(measurement.fluxes_e >= 0.0)
    assert measurement.spots is not None
    assert len(measurement.spots) == 4
    assert all(spot.shape == (18, 18) for spot in measurement.spots)
    assert all(np.all(np.isfinite(spot)) for spot in measurement.spots)
