"""Finite NumPy reference implementation of real Zernike pupil modes.

This module owns the repository's real-valued Zernike formulas, ordering, and
sampled-pupil normalization.  Canonical arrays are always finite and use zero
outside the pupil.  Installed legacy adapters restore their historical
NaN-outside representation without reimplementing the optical formulas.

The real-mode sign convention is explicit: positive azimuthal order uses
``cos(|m| theta)`` and negative order uses ``sin(|m| theta)``, with
``theta = atan2(y, x)``.  General mode dictionaries are ordered by increasing
radial order, then increasing ``|m|``; for non-zero ``|m|`` the positive mode
precedes the negative mode.
"""

from __future__ import annotations

from collections.abc import Mapping
import math
from numbers import Integral, Real

import numpy as np
from scipy.special import eval_jacobi as _eval_jacobi

from ...core import wavefront as _wavefront


__all__ = (
    "NativeModesError",
    "polar_pupil_coordinates",
    "normalize_mode_to_unit_pupil_rms",
    "zernike_named_modes",
    "zernike_radial",
    "zernike_nm",
    "generate_zernike_modes",
    "number_of_zernike_modes",
    "synthesize_modes",
    "mode_inner_product",
    "mode_gram_matrix",
)


class NativeModesError(ValueError):
    """Raised when native mode geometry or normalization is invalid."""


def polar_pupil_coordinates(
    x_m: np.ndarray,
    y_m: np.ndarray,
    telescope_diameter_m: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Return immutable dimensionless radius and polar angle arrays.

    ``x_m`` varies along columns and ``y_m`` along rows.  The returned radius
    is normalized by the pupil radius, so the geometric pupil edge is
    ``rho == 1``.  No aperture mask is applied here.
    """

    x = _real_array(x_m, label="x_m")
    y = _real_array(y_m, label="y_m")
    if x.ndim != 2 or y.shape != x.shape:
        raise NativeModesError("x_m and y_m must be matching 2-D arrays.")
    if not np.all(np.isfinite(x)) or not np.all(np.isfinite(y)):
        raise NativeModesError("x_m and y_m must contain only finite values.")
    diameter = _positive_float(
        telescope_diameter_m,
        label="telescope_diameter_m",
    )
    # Preserve the frozen repository arithmetic rather than substituting
    # ``hypot``: byte-level legacy samples were generated by this explicit
    # square/sum/square-root sequence.
    rho = np.sqrt(x**2 + y**2) / (0.5 * diameter)
    theta = np.arctan2(y, x)
    return (
        _readonly_array(rho, dtype=float),
        _readonly_array(theta, dtype=float),
    )


def normalize_mode_to_unit_pupil_rms(
    mode: np.ndarray,
    pupil_mask: np.ndarray,
    *,
    remove_piston: bool = True,
    return_scale: bool = False,
) -> np.ndarray | tuple[np.ndarray, float]:
    """Normalize one sampled mode to unit pupil RMS.

    Parameters
    ----------
    mode, pupil_mask:
        Matching sampled arrays.  Illuminated values must be finite; values
        outside the pupil are ignored and canonicalized to zero.
    remove_piston:
        Subtract the discrete illuminated-sample mean exactly once before
        measuring and normalizing RMS.  This is the canonical modal default.
    return_scale:
        If true, return ``(normalized_mode, raw_rms)``.  The scale is the RMS
        of the input after the requested piston policy, so compatibility
        adapters can undo normalization without duplicating it.

    Returns
    -------
    numpy.ndarray or (numpy.ndarray, float)
        A byte-backed immutable finite map whose illuminated-sample RMS is
        one, and optionally its pre-normalization RMS scale.
    """

    values, pupil = _validated_mode_and_mask(mode, pupil_mask, label="mode")
    subtract = _boolean(remove_piston, label="remove_piston")
    report_scale = _boolean(return_scale, label="return_scale")
    finite_map = np.where(pupil, values, 0.0)
    if subtract:
        piston_removed = _wavefront.remove_piston(finite_map, pupil)
        finite_map = np.where(pupil, piston_removed, 0.0)
    scale = _wavefront.masked_rms(
        finite_map,
        pupil,
        remove_mean=False,
    )
    if not math.isfinite(scale) or scale <= 0.0:
        policy = " after piston removal" if subtract else ""
        raise NativeModesError(
            f"mode must have finite non-zero pupil RMS{policy}."
        )

    normalized = np.zeros(values.shape, dtype=float)
    normalized[pupil] = finite_map[pupil] / scale
    immutable = _readonly_array(normalized, dtype=float)
    if report_scale:
        return immutable, scale
    return immutable


def zernike_named_modes(
    rho: np.ndarray,
    theta: np.ndarray,
    mask: np.ndarray,
    include_piston: bool = False,
    normalized: bool = True,
) -> dict[str, np.ndarray]:
    """Return the frozen practical low-order real Zernike mode set.

    ``normalized=True`` applies the continuous unobscured-disk factors used
    historically by the repository.  It is distinct from sampled unit-pupil
    RMS normalization; :func:`normalize_mode_to_unit_pupil_rms` is the sole
    implementation of the latter.
    """

    radius, angle, pupil = _validated_polar_pupil(rho, theta, mask)
    keep_piston = _boolean(include_piston, label="include_piston")
    use_continuous_normalization = _boolean(normalized, label="normalized")
    safe_radius = np.where(pupil, radius, 0.0)
    safe_angle = np.where(pupil, angle, 0.0)
    x = safe_radius * np.cos(safe_angle)
    y = safe_radius * np.sin(safe_angle)
    r2 = safe_radius**2

    if use_continuous_normalization:
        modes = {
            "piston": np.ones_like(safe_radius),
            "tip_x": 2.0 * x,
            "tip_y": 2.0 * y,
            "defocus": np.sqrt(3.0) * (2.0 * r2 - 1.0),
            "astig_45": np.sqrt(6.0) * 2.0 * x * y,
            "astig_0": np.sqrt(6.0) * (x**2 - y**2),
            "coma_x": np.sqrt(8.0) * (3.0 * r2 - 2.0) * x,
            "coma_y": np.sqrt(8.0) * (3.0 * r2 - 2.0) * y,
            "trefoil_x": np.sqrt(8.0) * (x**3 - 3.0 * x * y**2),
            "trefoil_y": np.sqrt(8.0) * (3.0 * x**2 * y - y**3),
            "spherical": np.sqrt(5.0) * (6.0 * r2**2 - 6.0 * r2 + 1.0),
        }
    else:
        modes = {
            "piston": np.ones_like(safe_radius),
            "tip_x": x,
            "tip_y": y,
            "defocus": 2.0 * r2 - 1.0,
            "astig_45": 2.0 * x * y,
            "astig_0": x**2 - y**2,
            "coma_x": (3.0 * r2 - 2.0) * x,
            "coma_y": (3.0 * r2 - 2.0) * y,
            "trefoil_x": x**3 - 3.0 * x * y**2,
            "trefoil_y": 3.0 * x**2 * y - y**3,
            "spherical": 6.0 * r2**2 - 6.0 * r2 + 1.0,
        }

    if not keep_piston:
        modes.pop("piston")
    return {
        name: _finite_pupil_map(values, pupil)
        for name, values in modes.items()
    }


def zernike_radial(n: int, m: int, rho: np.ndarray) -> np.ndarray:
    """Return the stable Jacobi-polynomial radial factor ``R_n^|m|``."""

    radial_order = _nonnegative_integer(n, label="n")
    azimuthal_order = abs(_integer(m, label="m"))
    if radial_order < azimuthal_order:
        raise NativeModesError("Zernike mode requires n >= |m|.")
    if (radial_order - azimuthal_order) % 2 != 0:
        raise NativeModesError("Zernike mode requires n - |m| to be even.")

    radius = _real_array(rho, label="rho")
    if not np.all(np.isfinite(radius)):
        raise NativeModesError("rho must contain only finite values.")
    radial_index = (radial_order - azimuthal_order) // 2
    result = (
        (-1.0) ** radial_index
        * radius**azimuthal_order
        * _eval_jacobi(
            radial_index,
            float(azimuthal_order),
            0.0,
            1.0 - 2.0 * radius**2,
        )
    )
    if not np.all(np.isfinite(result)):
        raise NativeModesError("Zernike radial evaluation produced non-finite values.")
    return _readonly_array(result, dtype=float)


def zernike_nm(
    n: int,
    m: int,
    rho: np.ndarray,
    theta: np.ndarray,
    mask: np.ndarray,
    normalization: bool = True,
) -> np.ndarray:
    """Return one finite, real-valued Zernike map in the frozen sign convention."""

    radial_order = _nonnegative_integer(n, label="n")
    signed_azimuthal_order = _integer(m, label="m")
    abs_m = abs(signed_azimuthal_order)
    radius, angle, pupil = _validated_polar_pupil(rho, theta, mask)
    normalize = _boolean(normalization, label="normalization")
    safe_radius = np.where(pupil, radius, 0.0)
    safe_angle = np.where(pupil, angle, 0.0)
    radial = np.asarray(
        zernike_radial(radial_order, abs_m, safe_radius),
        dtype=float,
    )

    if signed_azimuthal_order == 0:
        values = radial
        if normalize:
            values = values * np.sqrt(radial_order + 1.0)
    elif signed_azimuthal_order > 0:
        values = radial * np.cos(abs_m * safe_angle)
        if normalize:
            values = values * np.sqrt(2.0 * (radial_order + 1.0))
    else:
        values = radial * np.sin(abs_m * safe_angle)
        if normalize:
            values = values * np.sqrt(2.0 * (radial_order + 1.0))

    return _finite_pupil_map(values, pupil)


def generate_zernike_modes(
    rho: np.ndarray,
    theta: np.ndarray,
    mask: np.ndarray,
    max_radial_order: int = 6,
    include_piston: bool = False,
    normalization: bool = True,
) -> dict[str, np.ndarray]:
    """Generate all real Zernike modes through one radial order.

    Ordering is radial order, increasing absolute azimuthal order, then
    positive before negative azimuthal sign.
    """

    maximum = _nonnegative_integer(max_radial_order, label="max_radial_order")
    keep_piston = _boolean(include_piston, label="include_piston")
    normalize = _boolean(normalization, label="normalization")
    # Validate the shared sampled pupil before an empty/default traversal and
    # reuse the original inputs so zernike_nm remains the single formula owner.
    _validated_polar_pupil(rho, theta, mask)

    modes: dict[str, np.ndarray] = {}
    for radial_order in range(maximum + 1):
        for m_abs in range(radial_order + 1):
            if (radial_order - m_abs) % 2 != 0:
                continue
            if radial_order == 0 and m_abs == 0:
                if keep_piston:
                    modes["Z0_+0"] = zernike_nm(
                        radial_order,
                        0,
                        rho,
                        theta,
                        mask,
                        normalization=normalize,
                    )
                continue
            if m_abs == 0:
                modes[f"Z{radial_order}_+0"] = zernike_nm(
                    radial_order,
                    0,
                    rho,
                    theta,
                    mask,
                    normalization=normalize,
                )
            else:
                modes[f"Z{radial_order}_+{m_abs}"] = zernike_nm(
                    radial_order,
                    +m_abs,
                    rho,
                    theta,
                    mask,
                    normalization=normalize,
                )
                modes[f"Z{radial_order}_-{m_abs}"] = zernike_nm(
                    radial_order,
                    -m_abs,
                    rho,
                    theta,
                    mask,
                    normalization=normalize,
                )
    return modes


def number_of_zernike_modes(
    max_radial_order: int,
    include_piston: bool = False,
) -> int:
    """Return the number of real modes through one radial order."""

    maximum = _nonnegative_integer(max_radial_order, label="max_radial_order")
    keep_piston = _boolean(include_piston, label="include_piston")
    total = (maximum + 1) * (maximum + 2) // 2
    if not keep_piston:
        total -= 1
    return int(total)


def synthesize_modes(
    modes: Mapping[str, np.ndarray],
    coefficients: Mapping[str, float],
    pupil_mask: np.ndarray,
    *,
    remove_piston: bool = False,
) -> np.ndarray:
    """Synthesize a finite modal map in mapping insertion order."""

    names, sampled_modes, pupil = _validated_mode_mapping(modes, pupil_mask)
    if not isinstance(coefficients, Mapping):
        raise NativeModesError("coefficients must be a mapping.")
    subtract = _boolean(remove_piston, label="remove_piston")
    result = np.zeros(pupil.shape, dtype=float)
    for name, coefficient in coefficients.items():
        if name not in sampled_modes:
            raise NativeModesError(
                f"Mode {name!r} is not available. Available modes: {list(names)}"
            )
        result += _finite_float(coefficient, label=f"coefficients[{name!r}]") * sampled_modes[name]
    result[~pupil] = 0.0
    if not np.all(np.isfinite(result)):
        raise NativeModesError("modal synthesis produced non-finite values.")
    if subtract:
        piston_removed = _wavefront.remove_piston(result, pupil)
        return _readonly_array(
            np.where(pupil, piston_removed, 0.0),
            dtype=float,
        )
    return _readonly_array(result, dtype=float)


def mode_inner_product(
    first: np.ndarray,
    second: np.ndarray,
    pupil_mask: np.ndarray,
) -> float:
    """Return the discrete illuminated-sample mean product of two maps."""

    first_values, pupil = _validated_mode_and_mask(
        first,
        pupil_mask,
        label="first",
    )
    second_values, second_pupil = _validated_mode_and_mask(
        second,
        pupil_mask,
        label="second",
    )
    if not np.array_equal(pupil, second_pupil):  # Defensive; same input mask.
        raise NativeModesError("pupil masks do not match.")
    products = first_values[pupil] * second_values[pupil]
    if not np.all(np.isfinite(products)):
        raise NativeModesError("mode inner product produced non-finite values.")
    return float(np.mean(products))


def mode_gram_matrix(
    modes: Mapping[str, np.ndarray],
    pupil_mask: np.ndarray,
) -> tuple[np.ndarray, tuple[str, ...]]:
    """Return an immutable discrete Gram matrix and its ordered mode IDs."""

    names, sampled_modes, pupil = _validated_mode_mapping(modes, pupil_mask)
    gram = np.empty((len(names), len(names)), dtype=float)
    for row, first_name in enumerate(names):
        first = sampled_modes[first_name][pupil]
        for column, second_name in enumerate(names):
            products = first * sampled_modes[second_name][pupil]
            if not np.all(np.isfinite(products)):
                raise NativeModesError("mode Gram matrix produced non-finite values.")
            gram[row, column] = float(np.mean(products))
    return _readonly_array(gram, dtype=float), names


def _validated_polar_pupil(
    rho: object,
    theta: object,
    mask: object,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    radius = _real_array(rho, label="rho")
    angle = _real_array(theta, label="theta")
    pupil = _mask(mask, shape=radius.shape, label="mask")
    if angle.shape != radius.shape:
        raise NativeModesError("rho, theta, and mask must have identical shapes.")
    if not np.any(pupil):
        raise NativeModesError("mask must contain at least one pupil sample.")
    if not np.all(np.isfinite(radius[pupil])):
        raise NativeModesError("rho must be finite inside the pupil.")
    if not np.all(np.isfinite(angle[pupil])):
        raise NativeModesError("theta must be finite inside the pupil.")
    return radius, angle, pupil


def _validated_mode_and_mask(
    mode: object,
    pupil_mask: object,
    *,
    label: str,
) -> tuple[np.ndarray, np.ndarray]:
    values = _real_array(mode, label=label)
    pupil = _mask(pupil_mask, shape=values.shape, label="pupil_mask")
    if values.ndim != 2:
        raise NativeModesError(f"{label} must be a 2-D sampled map.")
    if not np.any(pupil):
        raise NativeModesError("pupil_mask must contain at least one sample.")
    if not np.all(np.isfinite(values[pupil])):
        raise NativeModesError(f"{label} must be finite inside the pupil.")
    return values, pupil


def _validated_mode_mapping(
    modes: object,
    pupil_mask: object,
) -> tuple[tuple[str, ...], dict[str, np.ndarray], np.ndarray]:
    if not isinstance(modes, Mapping) or not modes:
        raise NativeModesError("modes must be a non-empty ordered mapping.")
    names = tuple(modes)
    if any(not isinstance(name, str) or not name for name in names):
        raise NativeModesError("mode names must be non-empty strings.")
    if len(names) != len(set(names)):
        raise NativeModesError("mode names must not contain duplicates.")
    first = _real_array(modes[names[0]], label=f"modes[{names[0]!r}]")
    pupil = _mask(pupil_mask, shape=first.shape, label="pupil_mask")
    if first.ndim != 2 or not np.any(pupil):
        raise NativeModesError(
            "modes must be matching 2-D maps on a non-empty pupil."
        )
    sampled: dict[str, np.ndarray] = {}
    for name in names:
        values, actual_pupil = _validated_mode_and_mask(
            modes[name],
            pupil,
            label=f"modes[{name!r}]",
        )
        if values.shape != first.shape or not np.array_equal(actual_pupil, pupil):
            raise NativeModesError("all mode maps must share one sampled pupil.")
        sampled[name] = np.where(pupil, values, 0.0)
    return names, sampled, pupil


def _finite_pupil_map(values: object, pupil: np.ndarray) -> np.ndarray:
    result = np.where(pupil, np.asarray(values, dtype=float), 0.0)
    if not np.all(np.isfinite(result)):
        raise NativeModesError("mode generation produced non-finite values.")
    return _readonly_array(result, dtype=float)


def _real_array(values: object, *, label: str) -> np.ndarray:
    try:
        raw = np.asarray(values)
    except (TypeError, ValueError) as exc:
        raise NativeModesError(f"{label} must be a real numeric array.") from exc
    if (
        np.issubdtype(raw.dtype, np.bool_)
        or not np.issubdtype(raw.dtype, np.number)
        or np.issubdtype(raw.dtype, np.complexfloating)
    ):
        raise NativeModesError(f"{label} must be a real numeric array.")
    try:
        return np.asarray(raw, dtype=float)
    except (TypeError, ValueError, OverflowError) as exc:
        raise NativeModesError(f"{label} must be a real numeric array.") from exc


def _mask(values: object, *, shape: tuple[int, ...], label: str) -> np.ndarray:
    raw = np.asarray(values)
    if raw.dtype.kind != "b" or raw.shape != shape:
        raise NativeModesError(f"{label} must be a boolean array with shape {shape}.")
    return np.asarray(raw, dtype=bool)


def _readonly_array(values: object, *, dtype: object) -> np.ndarray:
    contiguous = np.ascontiguousarray(np.array(values, dtype=dtype, copy=True))
    immutable = np.frombuffer(contiguous.tobytes(order="C"), dtype=contiguous.dtype)
    return immutable.reshape(contiguous.shape)


def _integer(value: object, *, label: str) -> int:
    if not isinstance(value, Integral) or isinstance(value, (bool, np.bool_)):
        raise NativeModesError(f"{label} must be an integer.")
    return int(value)


def _nonnegative_integer(value: object, *, label: str) -> int:
    result = _integer(value, label=label)
    if result < 0:
        raise NativeModesError(f"{label} must be non-negative.")
    return result


def _finite_float(value: object, *, label: str) -> float:
    if not isinstance(value, Real) or isinstance(value, (bool, np.bool_)):
        raise NativeModesError(f"{label} must be a finite real scalar.")
    result = float(value)
    if not math.isfinite(result):
        raise NativeModesError(f"{label} must be a finite real scalar.")
    return result


def _positive_float(value: object, *, label: str) -> float:
    result = _finite_float(value, label=label)
    if result <= 0.0:
        raise NativeModesError(f"{label} must be positive.")
    return result


def _boolean(value: object, *, label: str) -> bool:
    if not isinstance(value, (bool, np.bool_)):
        raise NativeModesError(f"{label} must be a boolean.")
    return bool(value)
