"""Canonical, unit-explicit primitives shared across AO components."""

from .hashing import (
    HASH_SCHEMA_ID,
    HashingError,
    calibration_rows_hash,
    canonical_json_bytes,
    canonicalize_for_hash,
    command_coordinates_hash,
    component_config_hash,
    detector_plane_sampling_hash,
    geometry_hash,
    hash_calibration_rows,
    hash_command_coordinates,
    hash_component_config,
    hash_geometry,
    stable_array_descriptor,
    stable_hash,
)
from .geometry import GeometryError, PupilGeometry, build_pupil_geometry
from .protocols import (
    AtmosphereModel,
    CommandProjector,
    Controller,
    DeformableMirrorModel,
    RandomStreams,
    Reconstructor,
    SciencePropagator,
    ShackHartmannOpticsBackend,
    WavefrontSensor,
)
from .provenance import ALLOWED_SOURCE_CLASSES, Provenance, SourceClass
from .random import (
    DEFAULT_RANDOM_DOMAINS,
    DERIVATION_SCHEME_ID,
    NamedRandomStreams,
    RandomStreamError,
)
from .types import (
    DetectorFrame,
    DetectorPlaneSampling,
    DetectorTelemetry,
    DmCommandVector,
    DmSynthesisResult,
    MeasurementUnit,
    MeasurementVector,
    PsfResult,
    ReconstructionEstimate,
    SpotIntensityResult,
    WfsMeasurement,
)
from .wavefront import (
    mask_outside,
    masked_mean,
    masked_rms,
    opd_to_phase,
    phase_to_opd,
    remove_piston,
    validate_masked_finite,
)


__all__ = (
    "SourceClass",
    "ALLOWED_SOURCE_CLASSES",
    "Provenance",
    "GeometryError",
    "PupilGeometry",
    "build_pupil_geometry",
    "remove_piston",
    "masked_mean",
    "masked_rms",
    "phase_to_opd",
    "opd_to_phase",
    "mask_outside",
    "validate_masked_finite",
    "MeasurementUnit",
    "MeasurementVector",
    "DetectorPlaneSampling",
    "DetectorFrame",
    "DetectorTelemetry",
    "WfsMeasurement",
    "SpotIntensityResult",
    "PsfResult",
    "DmCommandVector",
    "DmSynthesisResult",
    "ReconstructionEstimate",
    "RandomStreams",
    "AtmosphereModel",
    "ShackHartmannOpticsBackend",
    "WavefrontSensor",
    "DeformableMirrorModel",
    "Reconstructor",
    "CommandProjector",
    "Controller",
    "SciencePropagator",
    "DEFAULT_RANDOM_DOMAINS",
    "DERIVATION_SCHEME_ID",
    "NamedRandomStreams",
    "RandomStreamError",
    "HASH_SCHEMA_ID",
    "HashingError",
    "stable_array_descriptor",
    "canonicalize_for_hash",
    "canonical_json_bytes",
    "stable_hash",
    "geometry_hash",
    "detector_plane_sampling_hash",
    "calibration_rows_hash",
    "command_coordinates_hash",
    "component_config_hash",
    "hash_geometry",
    "hash_calibration_rows",
    "hash_command_coordinates",
    "hash_component_config",
)
