"""Silent compatibility shim for :mod:`shwfs_ao.legacy.pwfs_forward`."""

from shwfs_ao.legacy import pwfs_forward as _implementation
from shwfs_ao.legacy.pwfs_forward import (
    add_detector_noise,
    add_tilt_phase,
    aligned_pupil_images,
    calibrate_pwfs_interaction_matrix,
    check_pwfs_geometry,
    extract_cutout,
    fft2c,
    ifft2c,
    make_aligned_pupil_mask,
    make_modulation_points,
    make_pwfs_grid,
    np,
    pupil_image_centers,
    pwfs_detector_measurement_from_phase,
    pwfs_detector_signal_from_phase,
    pwfs_intensity,
    pwfs_measurement_from_phase,
    pwfs_reference_signal,
    pwfs_signal_from_intensity,
    pwfs_signal_from_phase,
    pwfs_signal_maps_from_intensity,
    pyramid_phase_mask,
)

__all__ = (
    "add_detector_noise",
    "add_tilt_phase",
    "aligned_pupil_images",
    "calibrate_pwfs_interaction_matrix",
    "check_pwfs_geometry",
    "extract_cutout",
    "fft2c",
    "ifft2c",
    "make_aligned_pupil_mask",
    "make_modulation_points",
    "make_pwfs_grid",
    "np",
    "pupil_image_centers",
    "pwfs_detector_measurement_from_phase",
    "pwfs_detector_signal_from_phase",
    "pwfs_intensity",
    "pwfs_measurement_from_phase",
    "pwfs_reference_signal",
    "pwfs_signal_from_intensity",
    "pwfs_signal_from_phase",
    "pwfs_signal_maps_from_intensity",
    "pyramid_phase_mask",
)
