"""Silent compatibility shim for :mod:`shwfs_ao.legacy.synthetic_instrument_data`."""

from shwfs_ao.legacy import synthetic_instrument_data as _implementation
from shwfs_ao.legacy.synthetic_instrument_data import (
    ALLOWED_SOURCE_CLASSES,
    CentroidValidityConfig,
    DEFAULT_CENTROID_VALIDITY,
    DEFAULT_SOURCE_CLASS,
    DEFAULT_WFS_WAVELENGTH_M,
    DETECTOR_PRESETS,
    DetectorConfig,
    DetectorMeasurement,
    DetectorPreset,
    DetectorResponseMatrix,
    DetectorShwfsCalibration,
    MIN_VALID_CENTROID_FRACTION,
    Sequence,
    ShwfsGeometryConfig,
    SyntheticInstrumentError,
    add_configured_detector_noise,
    build_detector_shwfs_calibration,
    build_tilt_response_matrix,
    centroid,
    centroid_quality,
    crop_center,
    dataclass,
    detector_preset,
    lenslet_spot_from_phase,
    make_bad_pixel_mask,
    make_pupil_grid_and_mask,
    math,
    measure_detector_shwfs,
    nominal_lenslet_sampling_shape,
    np,
    phase_tilt_map_rad,
    sample_centroid_noise,
    subaperture_masks,
    zero_phase_centroid_rms_px,
)

if hasattr(_implementation, "annotations"):
    annotations = _implementation.annotations

__all__ = (
    "ALLOWED_SOURCE_CLASSES",
    "CentroidValidityConfig",
    "DEFAULT_CENTROID_VALIDITY",
    "DEFAULT_SOURCE_CLASS",
    "DEFAULT_WFS_WAVELENGTH_M",
    "DETECTOR_PRESETS",
    "DetectorConfig",
    "DetectorMeasurement",
    "DetectorPreset",
    "DetectorResponseMatrix",
    "DetectorShwfsCalibration",
    "MIN_VALID_CENTROID_FRACTION",
    "Sequence",
    "ShwfsGeometryConfig",
    "SyntheticInstrumentError",
    "add_configured_detector_noise",
    *(("annotations",) if hasattr(_implementation, "annotations") else ()),
    "build_detector_shwfs_calibration",
    "build_tilt_response_matrix",
    "centroid",
    "centroid_quality",
    "crop_center",
    "dataclass",
    "detector_preset",
    "lenslet_spot_from_phase",
    "make_bad_pixel_mask",
    "make_pupil_grid_and_mask",
    "math",
    "measure_detector_shwfs",
    "nominal_lenslet_sampling_shape",
    "np",
    "phase_tilt_map_rad",
    "sample_centroid_noise",
    "subaperture_masks",
    "zero_phase_centroid_rms_px",
)
