"""Stable wavefront-sensor component APIs."""

from .shack_hartmann import (
    DEFAULT_WFS_WAVELENGTH_M,
    NOISE_STREAM_IDENTITY_SCHEMA,
    DetectorLevelShackHartmannSensor,
    DetectorShackHartmannSensor,
    GeometricShackHartmannCalibration,
    GeometricShackHartmannError,
    GeometricShackHartmannSensor,
    NativeGeometricShackHartmannSensor,
    ShackHartmannCalibration,
    ShackHartmannCalibrationError,
    ShackHartmannGeometry,
    ShackHartmannGeometryError,
    ShackHartmannMeasurementError,
    ShackHartmannOpticsError,
    ShwfsGeometryConfig,
    build_detector_shack_hartmann_sensor,
    build_shack_hartmann_geometry,
    calibrate_zero_phase_reference,
    legacy_calibration_seeds,
    lenslet_indices_from_id,
    make_detector_plane_sampling,
    mean_subaperture_slopes,
    numerical_gradient,
    partition_pupil_geometry,
    row_ids_for_subapertures,
    shack_hartmann_calibration_hash,
    shack_hartmann_noise_stream_identity,
    subaperture_id,
    validate_optics_backend_result,
    validate_spot_intensity_result,
)


__all__ = (
    "DEFAULT_WFS_WAVELENGTH_M",
    "ShwfsGeometryConfig",
    "ShackHartmannGeometryError",
    "ShackHartmannGeometry",
    "build_shack_hartmann_geometry",
    "partition_pupil_geometry",
    "subaperture_id",
    "lenslet_indices_from_id",
    "ShackHartmannOpticsError",
    "make_detector_plane_sampling",
    "validate_spot_intensity_result",
    "validate_optics_backend_result",
    "NOISE_STREAM_IDENTITY_SCHEMA",
    "ShackHartmannCalibrationError",
    "ShackHartmannCalibration",
    "row_ids_for_subapertures",
    "calibrate_zero_phase_reference",
    "shack_hartmann_calibration_hash",
    "shack_hartmann_noise_stream_identity",
    "legacy_calibration_seeds",
    "ShackHartmannMeasurementError",
    "DetectorShackHartmannSensor",
    "DetectorLevelShackHartmannSensor",
    "build_detector_shack_hartmann_sensor",
    "GeometricShackHartmannError",
    "GeometricShackHartmannCalibration",
    "NativeGeometricShackHartmannSensor",
    "GeometricShackHartmannSensor",
    "numerical_gradient",
    "mean_subaperture_slopes",
)
